### ISSUE TITLE
Style Dashboard Frontend Based on Figma Design

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#106]
Hey team, it's high time we make the WebCrumbs dashboard look simple - but good! We've got a solid Figma design to guide us through this endeavor. Let's get this done and knock everyone's socks off, shall we?

_This issue replaces #64_

#### Requirements:
- Align with the Figma design found [here](https://www.figma.com/file/lwlAfp0wBpRnDKyxu2DRKj/webcrumbs?type=design&node-id=0%3A1&mode=design&t=NYdem9lvStsrftj2-1).
- Ensure the design is responsive and scales well on different screen sizes.
- Maintain accessibility standards.
- Test cross-browser compatibility.

#### To-Do
- [ ] Work on the `/admin` directory using Material UI (already installed)
- [ ] Implement color scheme, typography, spacing, roundings, etc., to mimic the figma design
- [ ] Add UI elements like buttons, cards, etc., and the same copy as the figma design

For a clearer picture, it will end up looking like this:

<img src="https://github.com/webcrumbs-community/webcrumbs/raw/main/src/img/Mac%20Monitor%20Faded.png"/>

This isn't just beautifying; it's all about enhancing user experience and usability. Trust me, they'll thank us later!

**Comment by jsimples** [comment]
I can take the lead on this one, and any help is appreciated!

**Comment by jsimples** [comment]
Hi, @Ashok-Kumar-dharanikota! Added a bunch of style to the admin. It's merged already. It's still missing the search bar and the user dropdown. I started it at NavBar.tsx but it's far from done. Let me know if you'd like to take a shot at it. I'll have more time to see it later today or tomorrow.

**Comment by Ashok-Kumar-dharanikota** [comment]
Yes! I would like to give it a shot.

**Comment by webcrumbs-community** [comment]
Nice work!! You can export the icons from the figma file.

**Comment by webcrumbs-community** [comment]
Looking good. Agree with the drop-down as it is for now. You can send a PR. Thanks!!

**Comment by jsimples** [comment]
@Ashok-Kumar-dharanikota, it's looking super sharp!! I'd just add some spacing in the menu dropdown, but I understand we'll be editing it later. Cool! Good for PR

**Comment by Ashok-Kumar-dharanikota** [comment]
I am out of my town right now, and will raise the PR Tomorrow evening.
