### ISSUE TITLE
Database Schema Design

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#4]
We're planning to create a database architecture for WebCrumbs that closely aligns with the structure of WordPress's database. This approach will help ease the transition for users moving from WordPress to WebCrumbs.

#### Tasks:
- [ ] Study [WordPress's database design](https://drawsql.app/templates/wordpress) to understand its tables, relations, and schema.
- [ ] Document key similarities and differences between WordPress's database design and what would be optimal for WebCrumbs.
- [ ] Create a draft database schema for WebCrumbs based on the findings.
- [ ] Open a discussion for community input on the proposed database schema.

This is a great opportunity to contribute to the foundational structure of WebCrumbs. Anyone interested in database design or who has experience with WordPress will find this task particularly engaging.

To contribute or learn more, check out the [WebCrumbs GitHub repo](https://github.com/webcrumbs-community/webcrumbs).

**Comment by trdxlucifer** [comment]
what kind of database  is required supabse or mongodb or maybe prisma ?

**Comment by webcrumbs-community** [comment]
We're working with MongoDB. Initially locally but eventually I'll create a production uri. Do you enjoy MongoDB or have any suggestions? Cheers!

**Comment by trdxlucifer** [comment]
i dont know about backend i have worked on firebase and supabase only i dont know nodejs and how to connect mongodb through it

**Comment by trdxlucifer** [comment]
Supabase is a great Firebase replacement that uses a PostgreSQL backend. Prisma is the next generation ORM built for Node. JS and Typescript this i found on google

**Comment by trdxlucifer** [comment]
is there anything i can contribute as front end

**Comment by webcrumbs-community** [comment]
You could continue working on the demo, if you'd like. Perhaps make the index a little bit like this: 

![image](https://github.com/webcrumbs-community/webcrumbs/assets/116091091/bd53e93e-536a-491d-a9be-fb69cfad28e9)

What do you think?
Cheers!

**Comment by webcrumbs-community** [comment]
Hi, @awaisarshd. That's great to hear. It's definitely an addition to the community. Let me think a little bit and I'll come back to you. Cheers!

**Comment by awaisarshd** [comment]
That's sounds like a plan. I will also look into it or maybe an alternative. And we can discuss further.

**Comment by webcrumbs-community** [comment]
@awaisarshd I've just rewritten the description of this issue. See if it makes sense and let me know if you'd like me to assign this to you. Cheers and thanks!

**Comment by awaisarshd** [comment]
@webcrumbs-community I have checked the description, please assign it to me.

**Comment by awaisarshd** [comment]
Hi @webcrumbs-community, do we have a Discord Server or Slack channel, for any quick discussion? or anything that we will have come to these comments or discussions section?

Btw, I have gone through the link you shared for the WordPress DB, it just contains the core CMS-related tables, I have seen other online provided details for the WP DB, and mostly have those tables and structure, which is good for a CMS but doesn't have information about the Plugin registry etc. So, I am installing WP locally to do some reverse engineering to understand how the Plugins work there. 

I have noted a few things and will post all the findings and recommendations with an initial draft of the schema soon.

**Comment by webcrumbs-community** [comment]
@awaisarshd Nice. No discord or slack channel yet. I may open it soon! I'll let you know. In the meanwhile, feel free to add any discussions here! Cheers

**Comment by aditya4196** [comment]
https://www.wpbeginner.com/beginners-guide/beginners-guide-to-wordpress-database-management-with-phpmyadmin/
I found the above link which comprises of information on how Wordpress uses the DBMS in their system.

**Comment by aditya4196** [comment]
@webcrumbs-community 
can you assign this story to me too. Im currently in the process of analyzing the databases used in WordPress based on the above link i sent and some more research.
I will work on creating a rough ER diagram on how the tables are linked

**Comment by awaisarshd** [comment]
Hi @aditya4196, thanks for the above article. It has the same tables which were shared by @webcrumbs-community as part of the initial description. 

Btw, i have reviewed the WP db, they dont save the Plugins details in the database. Everything is managed on the files bases. WP has a folder under `wp-content/plugins` and all the plugins installed are update there and used from that location only. 

Only info which is saved in the DB related to plugins is the which plugins are active. 

@aditya4196 Please check the this link and can view diagram of the WP tables: https://drawsql.app/templates/wordpress

**Comment by aditya4196** [comment]
Hmm understood, so they haven't kept any complexity for the DB

**Comment by webcrumbs-community** [comment]
What about the plug-in store that appears inside the admin panel? Perhaps it calls an external url that have a plug-in db. Don't know if that part is open source

**Comment by aditya4196** [comment]
I think, they are just triggering the plugins, the DBs are maintained by the plugins original owners

**Comment by aditya4196** [comment]
Just like how auth0 does

**Comment by aditya4196** [comment]
@awaisarshd I would like to assist you with the schema design. Can we work on it together in the evening?

**Comment by awaisarshd** [comment]
@webcrumbs-community, that store is managed externally. It's like a docker registry where people can publish their plugins and then it will automatically appear here. I am not exactly sure about the URL they use or where the list is hosted. But its not harder to find as their all the source code is open source.

**Comment by awaisarshd** [comment]
@aditya4196 sure, we can allow me sometime and i will setup something for us to share and work together.

**Comment by aditya4196** [comment]
@awaisarshd were you able to create any collab platform or you want me to create it as i have time now

**Comment by awaisarshd** [comment]
@aditya4196 I created this Discord server: https://discord.gg/GgaeFd4D

**Comment by Gurnav224** [comment]
Hello 👋, I'm Gurnav. I'm eager to dive into open source to gain real-world experience and expand my knowledge.

**Comment by awaisarshd** [comment]
@webcrumbs-community I have created PR #114 which has some proposed schema for the database. This has been done with the continued discussion and help from @aditya4196. 

Happy to discuss further what we have proposed.

**Comment by webcrumbs-community** [comment]
Great, guys, @awaisarshd and @aditya4196. I already checked and it looks great. It will help a lot with our next steps. I'd love to hear your suggestions on how we can proceed. I'm seeing some scopes that can be done in parallel. If you have any thoughts on that, reach me out!

**Comment by aditya4196** [comment]
As we build the modules, it would get more clear on refining the schema.

**Comment by awaisarshd** [comment]
@webcrumbs-community thanks, yes that's the plan. I will coordinate with @aditya4196  and see how we can move forward with this.
