### ISSUE TITLE
Create COUNTRIES.svg file at the main directory

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#77]
We're looking to add a new SVG file in the main directory, specifically for country flags. The idea is to make it as easy as possible to maintain and add new flags as the community grows.

#### Tasks:
- [ ] Review the country list available in the README.md file.
- [ ] Check out the CONTRIBUTORS.svg file as an example of SVG layout with multiple images.
- [ ] Create a new SVG file named `COUNTRIES.svg` in the main directory.
- [ ] Populate the SVG file with flag images corresponding to the countries listed in README.md.

This could be an excellent task for those familiar with SVG code or looking to sharpen their SVG skills. Your contribution would make it easier for everyone to identify the countries represented in our community.

For more information and to get involved, visit the [WebCrumbs GitHub repo](https://github.com/webcrumbs-community/webcrumbs).

_Originally posted by @webcrumbs-community in https://github.com/webcrumbs-community/webcrumbs/issues/8#issuecomment-1761301013 - with @marameref and @Blossomeze_

**Comment by Blossomeze** [comment]
I have created the COUNTRIES.svg file. I created a pull request so please do a review
